/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => AutoCorrecter
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  status_notices: true,
  api_key: "",
  autocorrect_on_enter: false
};
var AutoCorrecter = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    this.onKeyDown = this.onKeyDown.bind(this);
    this.registerDomEvent(document, "keydown", this.onKeyDown, true);
    this.addCommand({
      id: "autocorrect-current-line",
      name: "Autocorrect current line",
      editorCallback: async (_editor, view) => {
        if (view instanceof import_obsidian.MarkdownView) {
          await this.correctCurrentLine(view);
        }
      }
    });
    this.addSettingTab(new SettingTab(this.app, this));
    if (!this.settings.api_key) {
      new import_obsidian.Notice(
        "Please enter your Together.ai API key in the settings tab to use Obsidian AutoCorrect."
      );
    }
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign(
      {},
      DEFAULT_SETTINGS,
      await this.loadData()
    );
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  stripLeadingWhitespace(input) {
    const match = input.match(/^[\t ]*/);
    const leadingWhitespace = match ? match[0] : "";
    const parsedText = input.replace(/^[\t ]*/, "");
    return [leadingWhitespace, parsedText];
  }
  async onKeyDown(event) {
    if (event.key === "Enter" && this.settings.autocorrect_on_enter) {
      const view = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
      if (view) {
        void this.correctCurrentLine(view);
      }
    }
  }
  async correctCurrentLine(view) {
    const cursor = view.editor.getCursor();
    const text = view.editor.getLine(cursor.line);
    if (text.trim() === "") {
      return;
    }
    const [leadingWhitespace, parsedText] = this.stripLeadingWhitespace(text);
    let status = null;
    if (this.settings.status_notices) {
      status = new import_obsidian.Notice(
        "Correcting spelling on line " + (cursor.line + 1) + "...",
        0
      );
    }
    const response = await this.getLLMResponse(parsedText);
    if (response.corrected_spelling) {
      const correctedText = leadingWhitespace + response.corrected_spelling;
      view.editor.setLine(cursor.line, correctedText);
      if (status) {
        status.hide();
      }
    } else {
      if (status) {
        status.hide();
      }
      new import_obsidian.Notice(
        "Error correcting spelling. Make sure API key is correct and Internet is working."
      );
    }
  }
  async getLLMResponse(text) {
    const url = "https://api.groq.com/openai/v1/chat/completions";
    const apiKey = this.settings.api_key;
    const content = `Your task is to take input text that may contain spelling errors and correct those errors while
			preserving the original meaning, grammar, punctuation and formatting. The text may contain Markdown
			or other formatting which should be maintained in the output.
			
			<input_text>
			${text}
			</input_text>
			
			Provide the corrected version of the input text with all formatting perfectly preserved inside
			<corrected_text> tags. ONLY correct clear spelling mistakes. Do not make any other changes.
			Never add tags, hashtags, links, headings, or new markdown structure.
			
			Example format for your response:
  			<corrected_text>Corrected version of the input text with all formatting perfectly preserved.</corrected_text>`;
    const headers = {
      "Content-Type": "application/json",
      Authorization: `Bearer ${apiKey}`
    };
    const data = {
      model: "llama-3.3-70b-versatile",
      messages: [{ role: "user", content }]
    };
    const params = {
      method: "POST",
      headers,
      body: JSON.stringify(data),
      url
    };
    try {
      const response = await (0, import_obsidian.requestUrl)(params);
      console.log(response);
      const parsedResponse = response.json.choices[0].message.content.split("<corrected_text>")[1].split("</corrected_text>")[0].replace(/\n/g, "");
      return { corrected_spelling: parsedResponse };
    } catch (error) {
      console.error(error);
      return error;
    }
  }
};
var SettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Groq API Key").setDesc(
      "Create a account at https://www.groq.com/ and enter your API key for the plugin to work."
    ).addText(
      (text) => text.setPlaceholder("Enter your key").setValue(this.plugin.settings.api_key).onChange(async (value) => {
        this.plugin.settings.api_key = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Status Notices").setDesc("Show status notice popups when correcting spelling.").addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.status_notices).onChange(async (value) => {
        this.plugin.settings.status_notices = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Autocorrect on Enter").setDesc(
      "When enabled, pressing Enter also runs autocorrect on the current line."
    ).addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.autocorrect_on_enter).onChange(async (value) => {
        this.plugin.settings.autocorrect_on_enter = value;
        await this.plugin.saveSettings();
      });
    });
  }
};
